on:
  push:
    branches:
      - mlucas/nasa-ogc
  workflow_dispatch:

jobs:
  build_app_pack:
    environment: DIT
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4

      - name: Use OGC App Pack Generator Action
        uses: MAAP-Project/ogc-app-pack-generator@feature/create-action
        with:
          workflow-configuration-path: nasa/ogc/workflow_configuration.yml
          dockerfile-path: nasa/Dockerfile